# Generated by Django 3.0.7 on 2022-01-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='jong_order',
        ),
    ]
